# Prompt for necessary environment variables
$SERVER_PORT = Read-Host "Enter SERVER_PORT"
$ASTRA_DB_USERNAME = Read-Host "Enter ASTRA_DB_USERNAME"
$ASTRA_DB_KEYSPACE = Read-Host "Enter ASTRA_DB_KEYSPACE"
$ASTRA_DB_ID = Read-Host "Enter ASTRA_DB_ID"
$DATASTAX_ASTRA_PASSWORD = Read-Host "Enter DATASTAX_ASTRA_PASSWORD"
$DATASTAX_ASTRA_SCB_NAME = Read-Host "Enter DATASTAX_ASTRA_SCB_NAME"

# Save the environment variables to a .env file with Unix line endings
$envFilePath = ".env"
@"
SERVER_PORT=$SERVER_PORT
ASTRA_DB_USERNAME=$ASTRA_DB_USERNAME
ASTRA_DB_KEYSPACE=$ASTRA_DB_KEYSPACE
ASTRA_DB_ID=$ASTRA_DB_ID
DATASTAX_ASTRA_PASSWORD=$DATASTAX_ASTRA_PASSWORD
DATASTAX_ASTRA_SCB_NAME=$DATASTAX_ASTRA_SCB_NAME
"@ | Set-Content -Path $envFilePath -Encoding Ascii

# Build the Docker image
docker build -t stac-app `
  --build-arg ASTRA_DB_USERNAME=$ASTRA_DB_USERNAME `
  --build-arg ASTRA_DB_KEYSPACE=$ASTRA_DB_KEYSPACE `
  --build-arg ASTRA_DB_ID=$ASTRA_DB_ID `
  --build-arg DATASTAX_ASTRA_PASSWORD=$DATASTAX_ASTRA_PASSWORD `
  --build-arg DATASTAX_ASTRA_SCB_NAME=$DATASTAX_ASTRA_SCB_NAME `
  .
